apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 400
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
