# Localstorage - mongo-pvc
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  accessModes:
    - ReadWriteOnce  # Fixed indentation and missing space before mode
  resources:
    requests:
      storage: 20Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-storage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce  # Fixed indentation and missing space before mode
  hostPath:
    path: "/mnt/somenew/directory/structure"
    type: DirectoryOrCreate
